print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")
print("Mise à jour en attente")

